// Re-export everything from the investments-v2 shared data
// This keeps a single source of truth for asset catalog + formatting
export {
  type Asset,
  type AssetCategory,
  type AssetTicker,
  type Position,
  type LineChartDataPoint,
  type Transaction,
  ASSETS,
  CATEGORY_INFO,
  CATEGORY_BADGE_VARIANT,
  MOCK_POSITIONS,
  getAsset,
  getAssetsByCategory,
  getPopularAssets,
  getPosition,
  getPortfolioTotal,
  isVolatile,
  formatBRL,
  formatUSD,
  formatPercentChange,
  formatQuantity,
  getCurrencySymbol,
  generatePriceChartData,
  generateYieldChartData,
  generatePortfolioChartData,
  getMockTransactions,
} from '../../invest-2/shared/data'
